import { useState } from 'react';

const vessels = [
  { id: 'samudra', name: 'MT Samudra Shakti', imo: '9382147', type: 'Crude oil tanker', score: 92, dwt: '158,000 t', flag: 'India', reason: 'Passed 2.4 km from the origin zone 38 min before the inferred discharge window. A 14 min AIS gap overlaps the highest-probability point.' },
  { id: 'konkan', name: 'MT Konkan Pride', imo: '9720031', type: 'Product tanker', score: 81, dwt: '74,200 t', flag: 'India', reason: 'Crossed the outer origin ellipse 1h 12m before the window. Course alignment is strong, but continuous AIS coverage lowers anomaly confidence.' },
  { id: 'malabar', name: 'MV Malabar Crest', imo: '9298402', type: 'Bulk carrier', score: 63, dwt: '81,500 t', flag: 'India', reason: 'Trajectory passes through the wider hindcast envelope. Vessel class and stable AIS pattern make a discharge less likely.' },
  { id: 'godavari', name: 'MV Godavari Star', imo: '9511840', type: 'Container ship', score: 41, dwt: '68,100 t', flag: 'India', reason: 'Observed nearby after the probable origin window. Its heading and timing are inconsistent with the reconstructed source.' },
];

function Sidebar() {
  return <aside className="sidebar"><div className="brand"><span className="brand-mark">CW</span><span>COASTAL WATCH</span></div><div className="workspace-label">INDIAN COASTAL MONITORING</div><nav className="nav"><button className="nav-item active"><span>01</span> Incidents <b>04</b></button><button className="nav-item"><span>02</span> Vessel tracks</button><button className="nav-item"><span>03</span> Satellite archive</button><button className="nav-item"><span>04</span> Ocean model</button></nav><div className="sidebar-divider"/><div className="workspace-label">WATCHLISTS</div><button className="watch-item"><i className="status-dot critical"/> Mumbai offshore / active</button><button className="watch-item"><i className="status-dot"/> Kandla approaches</button><button className="watch-item"><i className="status-dot"/> Chennai anchorage</button><div className="sidebar-bottom"><div className="system-state"><i className="pulse"/> <span>Model services online</span><small>v0.8.4</small></div><button className="user-chip"><span className="avatar">AR</span><span><strong>Analyst Rao</strong><small>Coastal operations</small></span></button></div></aside>;
}

function Metric({ label, value, unit, foot, primary, children }) {
  return <article className={`metric-card ${primary ? 'primary' : ''}`}><div className="metric-label">{label} <span className="info">i</span></div>{children || <div className="metric-value">{value}<span>{unit}</span></div>}<div className="metric-foot">{foot}</div></article>;
}

function EvidenceMap({ mode, setMode }) {
  return <article className="panel map-panel"><div className="panel-header"><div><div className="panel-kicker">SPATIAL EVIDENCE</div><h2>Origin reconstruction</h2></div><div className="view-switcher"><button className={`view-tab ${mode === 'trajectory' ? 'active' : ''}`} onClick={() => setMode('trajectory')}>Trajectory</button><button className={`view-tab ${mode === 'satellite' ? 'active' : ''}`} onClick={() => setMode('satellite')}>Satellite</button></div></div><div className={`map-wrap ${mode === 'satellite' ? 'satellite-mode' : ''}`}><div className="map-grid"/><div className="map-label label-a">ARABIAN SEA</div><div className="map-label label-b">MUMBAI</div><div className="map-label label-c">GUJARAT</div><svg className="map-lines" viewBox="0 0 800 390" preserveAspectRatio="none" aria-label="Origin reconstruction map"><path className="coast" d="M78,0 C110,54 92,95 121,130 C151,166 103,211 128,258 C147,295 124,341 170,390 M666,0 C632,44 651,77 620,112 C598,138 641,187 614,230 C592,268 625,327 601,390"/><path className="border-line" d="M246,0 C285,75 259,140 279,199 C294,250 270,325 306,390"/><path className="origin-zone" d="M376,166 C414,143 480,148 505,182 C529,215 488,251 442,257 C394,263 350,223 358,192 C362,181 368,173 376,166Z"/><path className="drift-path" d="M451,209 C498,195 529,205 571,180 C617,153 640,141 689,114"/><path className="drift-path secondary" d="M450,211 C496,222 530,240 572,233 C617,226 641,201 689,190"/><path className="vessel-path" d="M212,315 C265,299 308,279 362,243 C388,225 411,215 445,207"/><path className="vessel-path" d="M538,46 C537,94 517,130 493,169 C475,192 462,202 445,207"/><circle className="origin-pulse" cx="445" cy="207" r="14"/><circle className="origin-dot" cx="445" cy="207" r="5"/><circle className="ship-dot" cx="212" cy="315" r="5"/><circle className="ship-dot" cx="538" cy="46" r="5"/></svg><button className="origin-hotspot" aria-label="Show probable origin details"><span className="origin-tooltip"><small>ORIGIN PROBABILITY</small><strong>18.72° N · 72.48° E</strong><small>17 Jun · 23:40 UTC</small></span></button><div className="map-legend"><span><i className="legend-origin"/>Probable origin</span><span><i className="legend-drift"/>Drift envelope</span><span><i className="legend-vessel"/>Vessel track</span></div></div><div className="map-footer"><div><span className="footer-label">HINDCAST MODEL</span><strong>OpenDrift · INCOIS currents</strong></div><div><span className="footer-label">WIND FIELD</span><strong>ERA5 reanalysis</strong></div><div><span className="footer-label">POSITION ERROR</span><strong>± 4.6 km</strong></div></div></article>;
}

function CandidateList({ selected, setSelected }) {
  return <article className="panel ranking-panel"><div className="panel-header"><div><div className="panel-kicker">AIS CORRELATION</div><h2>Potential sources <span className="count">06</span></h2></div><button className="filter-button">Last 48h⌄</button></div><div className="ranking-list">{vessels.map((vessel, index) => <button key={vessel.id} className={`vessel-row ${selected.id === vessel.id ? 'selected' : ''}`} onClick={() => setSelected(vessel)}><span className="rank">0{index + 1}</span><span className="vessel-icon">▲</span><span className="vessel-info"><strong>{vessel.name}</strong><small>IMO {vessel.imo} · {vessel.type}</small></span><span className={`score ${vessel.score > 70 ? 'high' : vessel.score > 50 ? 'medium' : 'low'}`}>{vessel.score}<span>/100</span></span><span className="row-arrow">›</span></button>)}</div><button className="all-vessels">View all candidates <span>→</span></button></article>;
}

function EvidencePanel({ vessel }) {
  return <article className="panel evidence-panel"><div className="panel-header"><div><div className="panel-kicker">SELECTED CANDIDATE</div><h2>{vessel.name}</h2></div><span className="status-tag">{vessel.score > 70 ? 'HIGH RELEVANCE' : vessel.score > 50 ? 'REVIEW' : 'LOW RELEVANCE'}</span></div><div className="candidate-summary"><div className="candidate-score"><strong>{vessel.score}</strong><span>/100<br/>correlation</span></div><div className="candidate-facts"><div><span>VESSEL TYPE</span><strong>{vessel.type}</strong></div><div><span>DWT</span><strong>{vessel.dwt}</strong></div><div><span>FLAG</span><strong>{vessel.flag}</strong></div></div></div><div className="evidence-bars">{[['Origin proximity', 96], ['Time compatibility', 91], ['Trajectory match', 88], ['Behavioural anomaly', 72]].map(([label, value]) => <div className="bar-row" key={label}><span>{label}</span><div className="bar"><i style={{ width: `${value}%` }}/></div><b>{value}</b></div>)}</div><div className="evidence-note"><span>!</span><p><strong>Why this vessel?</strong> {vessel.reason}</p></div></article>;
}

function App() {
  const [selected, setSelected] = useState(vessels[0]);
  const [mode, setMode] = useState('trajectory');
  const [exported, setExported] = useState(false);
  return <div className="app-shell"><Sidebar/><main className="main-content"><header className="topbar"><div className="breadcrumb"><span>INCIDENTS</span><b>/</b><strong>IN-2024-0618</strong></div><div className="top-actions"><span className="sync"><i/> Demo scenario · Indian west coast</span><button className={`export-button ${exported ? 'exported' : ''}`} onClick={() => { setExported(true); setTimeout(() => setExported(false), 1800); }}>{exported ? 'Brief ready ✓' : 'Export brief ↗'}</button></div></header><section className="incident-heading"><div><div className="eyebrow"><span className="live-dot"/> ACTIVE INVESTIGATION</div><h1>Arabian Sea slick</h1><p>Probable surface oil discharge · Detected 18 Jun 2024, 06:42 UTC</p></div><div className="heading-meta"><div><span>CASE OWNER</span><strong>A. Rao</strong></div><div><span>LAST UPDATED</span><strong>08:31 UTC</strong></div></div></section><section className="metrics-grid"><Metric label="SLICK CONFIDENCE" value="87.4" unit="%" primary foot="↗ 6.2% since first pass"/><Metric label="ESTIMATED AREA" value="12.8" unit=" km²" foot="+2.1 km² in 6h · model estimate"/><Metric label="ORIGIN WINDOW" foot="72% confidence"><div className="metric-value small">17 JUN <span>22:10–</span><br/>18 JUN <span>01:40</span></div></Metric><Metric label="CANDIDATE VESSELS" value="06" foot="2 high relevance"/></section><section className="analysis-grid"><EvidenceMap mode={mode} setMode={setMode}/><CandidateList selected={selected} setSelected={setSelected}/></section><section className="evidence-grid"><EvidencePanel vessel={selected}/><article className="panel timeline-panel"><div className="panel-header"><div><div className="panel-kicker">EVENT TRACE</div><h2>Evidence timeline</h2></div></div><div className="timeline"><div className="timeline-item"><time>18 JUN · 06:42</time><div className="timeline-marker satellite-marker">◌</div><div><strong>Satellite pass confirms slick</strong><p>Sentinel-1 IW · 12.8 km² segmented area</p></div></div><div className="timeline-item"><time>18 JUN · 04:10</time><div className="timeline-marker model-marker">⌁</div><div><strong>Hindcast converges on origin</strong><p>72% probability inside 9.6 km ellipse</p></div></div><div className="timeline-item"><time>18 JUN · 00:18</time><div className="timeline-marker ais-marker">▲</div><div><strong>{selected.name} enters origin zone</strong><p>Speed 11.2 kn · heading 247° · AIS gap follows</p></div></div><div className="timeline-item muted-item"><time>17 JUN · 22:10</time><div className="timeline-marker">·</div><div><strong>Earliest plausible discharge</strong><p>Derived from current and wind backtracking</p></div></div></div></article></section><footer className="page-footer"><span>COASTAL WATCH · INDIAN WEST COAST</span><span>Scores are investigative indicators, not legal findings.</span></footer></main></div>;
}

export default App;
